name: Deploy MkDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.1.1"
      
      - name: Install dependencies
        run: poetry install --no-root
      
      - name: Build and deploy
        run: poetry run mkdocs gh-deploy --force